### ISSUE TITLE
feat: Pig Dice Game 

### ISSUE THREAD

**Issue by chilouis** [FC-Team-6/team-fizzbuzz#2]
## Description
Pig Dice Game

1. 주사위를 사용하며, 각 턴마다 플레이어는 주사위를 굴립니다.
2. 각 주사위의 눈금은 1에서 6까지의 숫자입니다.
3. 플레이어가 주사위를 굴릴 때마다 다음과 같은 규칙이 적용됩니다:
- 1이 나오면, 해당 턴에 얻은 점수가 모두 사라지고 턴이 종료됩니다. 다음 플레이어의 차례가 됩니다.
- 2에서 6까지의 다른 숫자가 나오면, 나온 숫자를 현재 턴의 점수에 더할 수 있습니다. 
4. 플레이어는 턴을 끝낼 때마다 현재 점수를 자신의 총 점수에 더합니다.
5. 누군가가 특정한 점수(예: 50점)에 도달하면 게임이 종료되고 해당 플레이어가 승리합니다. 

## Task
<수정 전>
- [ ] 주사위를 굴려서 점수를 누적하며, 플레이어와 컴퓨터 간의 게임 시뮬레이션
- [ ] 간단한 룰(Description 3 참조)을 따라 턴을 진행
- [ ] 한 플레이어가 50점 이상을 얻을 때까지 게임을 반복하고, 승자를 결정하여 출력

<수정 후>
- [x] 게임 시뮬레이션을 위한 함수 정의 및 뼈대 구축
- [x] 플레이어 및 컴퓨터 턴에 대한 함수 정의

## References
- [Pig Dice Game](https://www.mathsweek.ie/2021/games/pig.html)
